/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   ft_make_common.c                                   :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: jmaing <jmaing@student.42seoul.kr>         +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2022/03/30 14:38:59 by jmaing            #+#    #+#             */
/*   Updated: 2022/03/31 12:04:29 by jmaing           ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include <stdbool.h>
#include <stdio.h>

static const char *const	g_header_content = "" \
	"# **************************************" \
								"************************************** #\n" \
	"#                                       " \
								"                                       #\n" \
	"#                                       " \
								"                  :::      ::::::::    #\n" \
	"#    Makefile                           " \
								"                :+:      :+:    :+:    #\n" \
	"#                                       " \
								"              +:+ +:+         +:+      #\n" \
	"#    By: makegen                        " \
								"            +#+  +:+       +#+         #\n" \
	"#                                       " \
								"          +#+#+#+#+#+   +#+            #\n" \
	"#    Created automatically by makegen   " \
								"               #+#    #+#              #\n" \
	"#    Updated never, and shouldn't happen" \
								"              ###   ########.fr        #\n" \
	"#                                       " \
								"                                       #\n" \
	"# **************************************" \
								"************************************** #\n" \
	"\n" \
	"# This file is generated by program. DO NOT EDIT THIS FILE DIRECTLY!\n\n" \
	"";

void	make_common_print_header(void);
void	make_common_print_variable(const char *name, const char *value);
void	make_common_print_rule(
			bool phony,
			const char *name,
			const char *dependencies,
			const char *recipe
			);

void	make_common_print_header(void)
{
	puts(g_header_content);
	make_common_print_variable("Q", "$(if $(filter 1,$(V) $(VERBOSE)),,@)");
	make_common_print_variable("MAKE", "make --no-print-directory");
}

void	make_common_print_variable(const char *name, const char *value)
{
	printf("%s := %s\n", name, value);
}

void	make_common_print_rule(
	bool phony,
	const char *name,
	const char *dependencies,
	const char *recipe
)
{
	bool		line_start;
	const char	*current;

	if (phony)
		printf(".PHONY: %s\n", name);
	if (!dependencies)
		dependencies = "";
	printf("%s: %s\n", name, dependencies);
	if (!recipe)
		return ;
	current = recipe;
	line_start = true;
	while (*current)
	{
		if (line_start)
		{
			putchar('\t');
			line_start = false;
		}
		putchar(*current);
		if (*current == '\n')
			line_start = true;
		current++;
	}
	putchar('\n');
}
