/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   ft_make_builddir.c                                 :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: jmaing <jmaing@student.42seoul.kr>         +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2022/03/30 11:10:03 by jmaing            #+#    #+#             */
/*   Updated: 2022/03/30 12:09:30 by jmaing           ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include <stdio.h>

static const char *const	g_makefile_contents = "" \
	// environment variable V=1 or VEREBOSE=1 to make verbose
	"Q := $(if $(filter 1,$(V) $(VERBOSE)),,@)\n" \
	\
	// note: cwd must be (project root)/builddir
	"SRC_DIR := ..\n" \
	// must use ar to make .a file (specified in subject.pdf)
	"AR := ar\n" \
	// c compiler - clang recommended (asan msan ubsan test)
	"CC := clang\n" \
	// required flags specified in subject.pdf
	"CFLAGS := -Wall -Wextra -Werror\n" \
	// for debugging purpose
	"CFLAGS += $(if $(filter 1,$(TEST)), " \
		"-Weverything -Wno-poison-system-directories -save-temps=obj,)\n" \
	// without bonus
	"NAME_BONUS := bonus.a\n" \
	// with bonus
	"NAME_BASIC := basic.a\n" \
	// ft_src_*.c is for libft, ft_src_*_bonus.c is only for bonus specifically
	"SRCS_BONUS := $(wildcard $(SRC_DIR)/ft_src_*.c)\n" \
	// exclude *_bouns.c from basic.a source
	"SRCS_BASIC := $(filter-out " \
		"$(wildcard $(SRC_DIR)/*_bonus.c), $(SRCS_BONUS))\n" \
	"SRC_PATH_PREFIX := $(SRC_DIR)/ft_src_\n" \
	// store temporary files in cwd (builddir)
	"OBJS_BONUS := $(patsubst $(SRC_PATH_PREFIX)%.c,%.o,$(SRCS_BONUS))\n" \
	"OBJS_BASIC := $(patsubst $(SRC_PATH_PREFIX)%.c,%.o,$(SRCS_BASIC))\n" \
	// dependency files generated by -MMD option
	"DEPS := $(OBJS_BONUS:.o=.d)\n" \
	\
	"all: $(NAME_BASIC) $(NAME_BASIC)\n" \
	".PHONY: all test_basic test_bonus\n" \
	\
	"$(NAME_BASIC): $(OBJS_BASIC)\n" \
	"	$(Q)rm -f $@^\n" \
	"	$(Q)$(AR) cr $@ $^\n" \
	"$(NAME_BONUS): $(OBJS_BONUS)\n" \
	"	$(Q)rm -f $@^\n" \
	"	$(Q)$(AR) cr $@ $^\n" \
	\
	"%.o: $(SRC_PATH_PREFIX)%.c\n" \
	"	$(Q)$(CC) $(CFLAGS) -c $< -o $@ -MMD\n" \
	\
	"-include $(DEPS)\n" \
	"";

int	main(void)
{
	printf("%s", g_makefile_contents);
	return (0);
}
