/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   ft_make_builddir.c                                 :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: jmaing <jmaing@student.42seoul.kr>         +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2022/03/30 11:10:03 by jmaing            #+#    #+#             */
/*   Updated: 2022/03/30 13:46:22 by jmaing           ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include <stdio.h>

static const char *const	g_makefile_contents = "" \
	"# This file is generated by program. don't edit it manually!\n\n" \
	// environment variable V=1 or VEREBOSE=1 to make verbose
	"Q := $(if $(filter 1,$(V) $(VERBOSE)),,@)\n" \
	\
	// note: cwd must be (project root)/builddir
	"SRC_DIR := ..\n" \
	// must use ar to make .a file (specified in subject.pdf)
	"AR := ar\n" \
	// c compiler - clang recommended (asan msan ubsan test)
	"CC := clang\n" \
	// required flags specified in subject.pdf
	"CFLAGS := -Wall -Wextra -Werror\n" \
	// for debugging purpose
	"CFLAGS += $(if $(filter 1,$(TEST)), " \
		"-Weverything -Wno-poison-system-directories -save-temps=obj,)\n" \
	// without bonus
	"NAME_BONUS := bonus.a\n" \
	// with bonus
	"NAME_BASIC := basic.a\n" \
	// ft_src_*.c is for libft, ft_src_*_bonus.c is only for bonus specifically
	"SRCS_BONUS := $(wildcard $(SRC_DIR)/ft_src_*.c)\n" \
	// exclude *_bouns.c from basic.a source
	"SRCS_BASIC := $(filter-out " \
		"$(wildcard $(SRC_DIR)/*_bonus.c), $(SRCS_BONUS))\n" \
	"SRC_PATH_PREFIX := $(SRC_DIR)/ft_src_\n" \
	// store temporary files in cwd (builddir)
	"OBJS_BONUS := $(patsubst $(SRC_PATH_PREFIX)%.c,%.o,$(SRCS_BONUS))\n" \
	"OBJS_BASIC := $(patsubst $(SRC_PATH_PREFIX)%.c,%.o,$(SRCS_BASIC))\n" \
	// dependency files generated by -MMD option
	"DEPS := $(OBJS_BONUS:.o=.d)\n" \
	\
	// rule `all`, `test` is for debug, not indirectly called in automated test
	"all: $(NAME_BASIC) $(NAME_BASIC)\n" \
	// copy to *_tested.a after test
	"basic_tested.a: test_basic\n" \
	"	$(Q)cp basic.a basic_tested.a\n" \
	"bonus_tested.a: test_bonus\n" \
	"	$(Q)cp bonus.a bonus_tested.a\n" \
	// self test
	"test: test_basic test_bonus\n" \
	"test_basic: basic.a tester_common_basic tester_only_basic\n" \
	"	$(Q)./tester_common_basic\n" \
	"	$(Q)./tester_only_basic\n" \
	"test_bonus: bonus.a tester_common_bonus tester_only_bonus\n" \
	"	$(Q)./tester_common_bonus\n" \
	"	$(Q)./tester_only_bonus\n" \
	".PHONY: all test test_basic test_bonus\n" \
	// tester
	"tester_common_%: tester_common.a %.a\n" \
	"	$(Q)gcc -o $@ -Wall -Wextra -Werror $^\n" \
	"tester_only_%: tester_%.a %.a\n" \
	"	$(Q)gcc -o $@ -Wall -Wextra -Werror $^\n" \
	"tester_%.a: | builddir_tester_%\n" \
	"	$(Q)make -C builddir_$(@:.a=)\n" \
	"	$(Q)cp builddir_$(@:.a=)/tester.a ./$@\n" \
	"builddir_tester_%:\n" \
	"	$(Q)rm -rf tmp/$@\n" \
	"	$(Q)mkdir -p tmp/$@\n" \
	"	$(Q)gcc -Wall -Wextra -Werror -o tmp/$@/makegen $(SRC_DIR)/ft_make_$@.c\n" \
	"	$(Q)tmp/$@/makegen > tmp/$@/Makefile\n" \
	"	$(Q)rm -f tmp/$@/makegen\n" \
	"	$(Q)mv tmp/$@ .\n" \
	\
	// final build result - basic.a, bonus.a
	"$(NAME_BASIC): $(OBJS_BASIC)\n" \
	"	$(Q)rm -f $@\n" \
	"	$(Q)$(AR) cr $@ $^\n" \
	"$(NAME_BONUS): $(OBJS_BONUS)\n" \
	"	$(Q)rm -f $@\n" \
	"	$(Q)$(AR) cr $@ $^\n" \
	\
	// rule for *.o
	"%.o: $(SRC_PATH_PREFIX)%.c\n" \
	"	$(Q)$(CC) $(CFLAGS) -c $< -o $@ -MMD\n" \
	\
	"-include $(DEPS)\n" \
	"";

int	main(void)
{
	printf("%s", g_makefile_contents);
	return (0);
}
